name: mttn_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html_view:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
