name: mttn_app
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.2.2-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # AndroidX supported plugins
  firebase_messaging: 5.0.3
  firebase_database: 3.0.2
  firebase_storage: 3.0.1
  share: 0.6.1+1
  url_launcher: 5.0.3
  flutter_cache_manager: ^1.1.0
  device_info: 0.4.0+2
  firebase_auth: ^0.14.0+3
  provider:
  rxdart: ^0.22.1+1

  # Non-AndroidX supported plugins
  cached_network_image: 1.1.0
  font_awesome_flutter: 8.5.0 
  flutter_html: 0.10.1+hotfix.1
  http: 0.12.0+2
  percent_indicator: ^1.0.13
  progress_button: ^0.0.1
  flutter_parallax: ^0.1.2
  flare_flutter: 1.0.2
  dynamic_theme: ^1.0.1
  transparent_image: 1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - facebook.png
    - instagram.png
    - youtube.png
    - earthlogin.flr
    - freshers.png
    - ic_launcher.png
    - ic_launcher_white.png
    - avatar.jpg

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
    - family: Product-Sans
      fonts: 
        - asset: fonts/Product-Sans-Regular.ttf
        - asset: fonts/Product-Sans-Italic.ttf
        - asset: fonts/Product-Sans-Bold.ttf
    - family: Cabin
      fonts: 
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-Italic.ttf
        - asset: fonts/Cabin-Bold.ttf    
    
